-- add hostName
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, file_max_size, file_min_ratio, file_max_ratio) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'core'),'hostName', 'STRING', 0, 1, NOW(), 'system', NOW(), 'system', '^[A-Za-z0-9 ]{1,15}$', 'Host name must be alphanumeric and have a max length of 15 characters', 1, 0, NULL, 'Host Name', 0, 0, 28, 'Host name to print on the receipt. Must be alphanumeric and under 15 characters long.', NULL, NULL, NULL);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'hostName' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')));
INSERT IGNORE INTO profile_data (profile_id, data_element_id, datavalue, version, updated_at, updated_by, created_at, created_by, approved, overriden, is_encrypted, not_overridable) values (1, (SELECT data_element_id FROM data_element WHERE name = 'hostName' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')), 'NI', 1, NOW(), 'NISuper', NOW(), 'NISuper', 1, 1, 0, 0) ON DUPLICATE KEY UPDATE datavalue=datavalue, updated_at = updated_at;
-- add hostUrl
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, file_max_size, file_min_ratio, file_max_ratio) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'core'),'hostUrl', 'STRING', 0, 1, NOW(), 'system', NOW(), 'system', NULL, 'Host url must not be left blank', 0, 0, NULL, 'Host URL', 0, 0, 29, 'Host url thats printed on the PEDs about page. Must not be empty.', NULL, NULL, NULL);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'hostUrl' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')));
INSERT IGNORE INTO profile_data (profile_id, data_element_id, datavalue, version, updated_at, updated_by, created_at, created_by, approved, overriden, is_encrypted, not_overridable) values (1, (SELECT data_element_id FROM data_element WHERE name = 'hostUrl' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')), 'http://www.network.ae', 1, NOW(), 'NISuper', NOW(), 'NISuper', 1, 1, 0, 0) ON DUPLICATE KEY UPDATE datavalue=datavalue, updated_at = updated_at;
-- add backgroundImage
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, file_max_size, file_min_ratio, file_max_ratio) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'core'),'backgroundImage', 'FILE', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL, 0, 0, NULL, 'Background Image', 0, 0, 30, 'Image to use as the PEDs background. The chosen file should have a similar aspect ratio to a PED screen.', 50000, 0.56, 0.6);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'backgroundImage' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')));
-- add bootImage
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, file_max_size, file_min_ratio, file_max_ratio) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'core'),'bootImage', 'FILE', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL, 0, 0, NULL, 'Boot Image', 0, 0, 26, 'Image to use on the PEDs boot screen', 50000, NULL, NULL);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'chain_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'bootImage' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')));
-- add bootImageBackground
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, file_max_size, file_min_ratio, file_max_ratio) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'core'),'bootImageBackground', 'STRING', 1, 1, NOW(), 'system', NOW(), 'system', '^#(?:[0-9a-fA-F]{3}){1,2}$', 'The background colour should be in hexadecimal format (e.g. #FFFFFF)', 1, 0, NULL, 'Boot Image Background Colour', 0, 0, 27, 'Background colour for the boot screen, this should be a hexadecimal colour (e.g #FFFFFF)', NULL, NULL, NULL);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'chain_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'bootImageBackground' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core')));
