UPDATE data_element SET displayname_en = 'Name' WHERE name = 'name' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Address Line 1' WHERE name = 'addressLine1' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Address Line 2' WHERE name = 'addressLine2' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Receipt Footer Line 1' WHERE name = 'receiptFooterLine1' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Receipt Footer Line 2' WHERE name = 'receiptFooterLine2' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Min Local Level' WHERE name = 'minLocalLevel' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'logging');
UPDATE data_element SET displayname_en = 'Min Upload Level' WHERE name = 'minUploadLevel' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'logging');
UPDATE data_element SET displayname_en = 'Max Upload Size' WHERE name = 'maxUploadSize' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'logging');
UPDATE data_element SET displayname_en = 'Display For' WHERE name = 'displayFor' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'receipt');
UPDATE data_element SET displayname_en = 'Retry Time' WHERE name = 'retryTime' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'reversal');
UPDATE data_element SET displayname_en = 'Retries' WHERE name = 'retries' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'reversal');
UPDATE data_element SET displayname_en = 'Time' WHERE name = 'time' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'Auto' WHERE name = 'auto' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'Soft Limit' WHERE name = 'softLimit' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'Hard Limit' WHERE name = 'hardLimit' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'Card Definitions' WHERE name = 'cardDefinitions' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Active' WHERE name = 'active' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Available' WHERE name = 'available' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'userMgmt');
UPDATE data_element SET displayname_en = 'Supervisor PIN' WHERE name = 'superPIN' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'userMgmt');
UPDATE data_element SET displayname_en = 'Terminal Country Code' WHERE name = 'terminalCountryCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Transaction Country Code' WHERE name = 'transactionCurrencyCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Retries' WHERE name = 'retries' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Terminal Config' WHERE name = 'terminalConfig' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contact ICS Config' WHERE name = 'contactIcsConfig' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contact Application Config Shared' WHERE name = 'contactApplicationConfigShared' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contact Application Config' WHERE name = 'contactApplicationConfigs' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contact Key Config' WHERE name = 'contactKeyConfigs' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contactless Kernel Config' WHERE name = 'ctlsKernelConfigs' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contactless Application Config Shared' WHERE name = 'ctlsApplicationConfigShared' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contactless Application Config' WHERE name = 'ctlsApplicationConfigs' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Contactless Key Config' WHERE name = 'ctlsKeyConfigs' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'DCC Handover Timer' WHERE name = 'dccHandoverTimer' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'DCC Enabled' WHERE name = 'dccEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'DCC Min Value' WHERE name = 'dccMinValue' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'DCC Max Value' WHERE name = 'dccMaxValue' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'DCC Loval Bins' WHERE name = 'dccLocalBins' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Manual Entry Enabled' WHERE name = 'manualEntryEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Supervisor Only' WHERE name = 'supervisorOnly' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Screen Timeout' WHERE name = 'screenTimeout' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'Amount Entry Max' WHERE name = 'amountEntryMax' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'PAN Mask' WHERE name = 'panMask' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'Acquiring Institute ID' WHERE name = 'acquiringInstituteId' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Amex MID' WHERE name = 'amexMid' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Required Software Version' WHERE name = 'RequiredSoftwareVersion' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'X Read Max Prints' WHERE name = 'xReadMaxPrints' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'Z Read Max Prints' WHERE name = 'zReadMaxPrints' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'endOfDay');
UPDATE data_element SET displayname_en = 'DCC Provider' WHERE name = 'dccProvider' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Mode' WHERE name = 'mode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'EPOS Image' WHERE name = 'eposImage' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'DCC Contactless' WHERE name = 'dccContactless' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'modules');
UPDATE data_element SET displayname_en = 'Alipay Partner' WHERE name = 'alipayPartner' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'alipay');
UPDATE data_element SET displayname_en = 'Alipay Private Key' WHERE name = 'alipayPrivateKey' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'alipay');
UPDATE data_element SET displayname_en = 'Alipay MID' WHERE name = 'alipayMid' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'alipay');
UPDATE data_element SET displayname_en = 'Alipay MCC' WHERE name = 'alipayMcc' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'alipay');
UPDATE data_element SET displayname_en = 'EPOS Top Text' WHERE name = 'eposTopText' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'EPOS Bottom Text' WHERE name = 'eposBottomText' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Beep For Insertion' WHERE name = 'beepForInsertion' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'Beep For Removal' WHERE name = 'beepForRemoval' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'emv');
UPDATE data_element SET displayname_en = 'TMS Users' WHERE name = 'tmsUsers' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'userMgmt');
UPDATE data_element SET displayname_en = 'Property ID' WHERE name = 'propertyId' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'opi');
UPDATE data_element SET displayname_en = 'Workstation Number' WHERE name = 'workstationNumber' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'opi');
UPDATE data_element SET displayname_en = 'Use Confirmation Code' WHERE name = 'useConfirmationCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'pinset');
UPDATE data_element SET displayname_en = 'Time Zone Name' WHERE name = 'timezoneName' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'store');
UPDATE data_element SET displayname_en = 'Acquirer Logo' WHERE name = 'acquirerLogo' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'Allow Get PAN' WHERE name = 'allowGetPAN' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'opi');
UPDATE data_element SET displayname_en = 'Acquirer IIN' WHERE name = 'acquirerIIN' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'upiQr');
UPDATE data_element SET displayname_en = 'Forwarding IIN' WHERE name = 'forwardingIIN' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'upiQr');
UPDATE data_element SET displayname_en = 'Category Code' WHERE name = 'categoryCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'upiQr');
UPDATE data_element SET displayname_en = 'Country Code' WHERE name = 'countryCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'upiQr');
UPDATE data_element SET displayname_en = 'Available' WHERE name = 'available' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'offline');
UPDATE data_element SET displayname_en = 'Schemes' WHERE name = 'schemes' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'offline');
UPDATE data_element SET displayname_en = 'Online Refund' WHERE name = 'onlineRefund' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'core');
UPDATE data_element SET displayname_en = 'Total Limit' WHERE name = 'totalLimit' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'offline');
UPDATE data_element SET displayname_en = 'Upload Frequency' WHERE name = 'uploadFrequency' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'offline');
UPDATE data_element SET displayname_en = 'Offline Duration' WHERE name = 'offlineDuration' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'offline');
