DROP PROCEDURE IF EXISTS AddColumn;
DROP PROCEDURE IF EXISTS store_enrolment_PIN;
DROP PROCEDURE IF EXISTS store_reset_PIN;
DROP PROCEDURE IF EXISTS get_tid_page;
DROP PROCEDURE IF EXISTS log_tid_change;
DROP PROCEDURE IF EXISTS get_site_tids;