INSERT IGNORE INTO data_group (name, version, updated_at, updated_by, created_at, created_by, displayname_en) VALUES ('digitalReceipts', '1', now(), 'system', now(), 'system', 'Digital Receipts');
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'enabled', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'Enabled', 0, 0, 1, 'Main feature flag for the overall Digital Receipts feature. If disabled, none of the digital receipting features will be active', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'enabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'organizationCode', 'STRING', 0, 1, NOW(), 'system', NOW(), 'system', '^[0-9]{3}$', 'Value must be numerical and three digits long', 0, 0, '', 'Organization Code', 0, 0, 2, 'The organization code required by RMS. Without this, digital receipts will not function.', 0);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'organizationCode' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'smsEnabled', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'SMS Receipts', 0, 0, 3, 'If enabled, the PED will allow for phone number entry to support SMS Receipt requests', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'smsEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'emailEnabled', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'Email Receipts', 0, 0, 4, 'If enabled, the PED will allow for email entry to support Email Receipt requests', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'emailEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'qrEnabled', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'QR Receipts', 0, 0, 5, 'If enabled, the PED will allow for QR Code E-Receipt requests', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'qrEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'txnHistoryEnabled', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'Resend E-Receipts', 0, 0, 6, 'If enabled, the PED will support the re-sending of E-Receipts at the Transaction History. This must be used in conjunction with the other flags in this data group', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'txnHistoryEnabled' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'onScreenReceipt', 'BOOLEAN', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'On Screen Receipt', 0, 0, 7, 'When enabled, the merchant will be able to display an on-screen receipt from the digital receipt menu', 1);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'onScreenReceipt' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'termsCheckBoxText', 'STRING', 1, 1, NOW(), 'system', NOW(), 'system', '^.{0,100}$', 'Text must not be any greater than 100 characters', 0, 0, '', 'T&Cs Checkbox Text', 0, 0, 8, 'The agreement text to display next to the T&Cs checkbox on the email and SMS digital receipt screen. If blank, no agreement checkbox will be displayed', 0);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'termsCheckBoxText' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'termsText', 'STRING', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'T&Cs Text', 0, 0, 9, 'The full terms and conditions text to display on the email and SMS digital receipt screen. If blank, no agreement checkbox will be displayed', 0);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'termsText' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'phoneValidationTooltip', 'STRING', 1, 1, NOW(), 'system', NOW(), 'system', '^.{0,100}$', NULL , 0, 0, '', 'Phone validation tooltip', 0, 0, 10, 'The text to display underneath the phone number entry screen for digital receipts, prompting the customer on the required format', 0);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'phoneValidationTooltip' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
INSERT IGNORE INTO data_element(data_group_id, name, datatype, is_allow_empty, version, updated_at, updated_by, created_at, created_by, validation_expression, validation_message, front_end_validate, `unique`, options, displayname_en, is_encrypted, is_password, sort_order_in_group, tooltip, tid_overridable) VALUES ((SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts'), 'phoneValidationRegex', 'STRING', 1, 1, NOW(), 'system', NOW(), 'system', NULL, NULL , 0, 0, '', 'Phone validation REGEX', 0, 0, 11, 'How the phone number should be validated, using a regular expression. If empty, no validation will be carried out', 0);
INSERT IGNORE INTO data_element_locations_data_element(location_id, data_element_id) VALUES ((SELECT location_id FROM data_element_locations WHERE location_name = 'site_configuration'), (SELECT data_element_id FROM data_element WHERE name = 'phoneValidationRegex' AND data_group_id = (SELECT data_group_id FROM data_group WHERE name = 'digitalReceipts')));
call add_data_groups_to_tid_profiles
call add_data_groups_to_tid_profiles