set @profileId = 2856;
set @priority = (select priority from profile_type pt join profile p on p.profile_id = @profileId where p.profile_type_id = pt.profile_type_id);
drop temporary table if exists temp_site_table; 
delete tid_site from tid_site inner join site_profiles on site_profiles.site_id = tid_site.site_id where site_profiles.profile_id = @profileId;
delete tid_updates from tid_updates left outer join tid_site ts on ts.tid_id = tid_updates.tid_id where ts.tid_id is null;
delete tid_user_override from tid_user_override left outer join tid_site ts on ts.tid_id = tid_user_override.tid_id where ts.tid_id is null;
delete t from tid t left outer join tid_site ts on ts.tid_id = t.tid_id where ts.tid_id is null;
delete from chain_profiles where chain_profile_id = @profileId or acquirer_id = @profileId;
create temporary table if not exists temp_site_table select s.site_id from site s join site_profiles sp on sp.site_id = s.site_id where sp.profile_id = @profileId;
delete a from approvals a join site_profiles sp on sp.profile_id = a.profile_id join profile p on p.profile_id = sp.profile_id join profile_type pt on pt.profile_type_id = p.profile_type_id where sp.site_id in (select site_id from temp_site_table) and pt.priority <= @priority;
delete pd from profile_data pd join site_profiles sp on sp.profile_id = pd.profile_id join profile p on p.profile_id = sp.profile_id join profile_type pt on pt.profile_type_id = p.profile_type_id where sp.site_id in (select site_id from temp_site_table) and pt.priority <= @priority;
delete pd from profile_data pd where pd.profile_id = @profileId;
delete pdg from profile_data_group pdg join site_profiles sp on sp.profile_id = pdg.profile_id join profile p on p.profile_id = pdg.profile_id join profile_type pt on pt.profile_type_id = p.profile_type_id where sp.site_id in (select site_id from temp_site_table) and pt.priority <= @priority;
delete pdg from profile_data_group pdg where pdg.profile_id = @profileId;
delete sp from site_profiles sp join profile p on p.profile_id = sp.profile_id join profile_type pt on pt.profile_type_id = p.profile_type_id where sp.site_id in (select site_id from temp_site_table);
delete s from site s where s.site_id in (select site_id from temp_site_table); 
delete a from approvals a where profile_id = @profileId;
delete p from profile p where p.profile_id = @profileId;
drop temporary table if exists temp_site_table;