update data_element set max_length = 12 where name = "merchantNo";
update data_element set validation_expression = '^\\d{12}$' where name = "merchantNo";
update data_element set validation_message = "Must be numeric and 12 digits long" where name = "merchantNo";
update data_element set is_allow_empty = 0 where name = "merchantNo";
update data_element set max_length = 23 where name = "name";
update data_element set validation_expression = '^.{1,23}$' where name = "name";
update data_element set validation_message = "Must be up to 23 characters long" where name = "name";
update data_element set is_allow_empty = 0 where name = "name";
update data_element set front_end_validate = 1 where name = "name";
update data_element set max_length = 25 where name = "addressLine1";
update data_element set validation_expression = '^.{1,25}$' where name = "addressLine1";
update data_element set validation_message = "Must be up to 25 characters long" where name = "addressLine1";
update data_element set is_allow_empty = 0 where name = "addressLine1";
update data_element set front_end_validate = 1 where name = "addressLine1";
update data_element set max_length = 25 where name = "addressLine2";
update data_element set validation_expression = '^.{1,25}$' where name = "addressLine2";
update data_element set validation_message = "Must be up to 25 characters long" where name = "addressLine2";
update data_element set is_allow_empty = 0 where name = "addressLine2";
update data_element set front_end_validate = 1 where name = "addressLine2";
update data_element set validation_expression = '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$' where name = "time";
update data_element set validation_message = "Must be in range of 00:00 to 23:59" where name = "time";
update data_element set options = "sale|refund|void|preAuth|gratuitySale|gratuityCompletion|alipay" where name = "active";
update data_element set options = "sale|refund|void|preAuth|gratuitySale|gratuityCompletion" where name = "supervisorOnly";
update data_element set is_allow_empty = 0 where name = "screenTimeout";
update data_element set options = "6,4|0,4" where name = "panMask";
update data_element set max_length = 10 where name = "amexMid";
update data_element set validation_expression = '^.{0,10}$' where name = "amexMid";
update data_element set validation_message = "Must no longer than 10 characters" where name = "amexMid";
update data_element set front_end_validate = 1 where name = "amexMid";
update data_element set validation_expression = '^\\d+$' where name = "xReadMaxPrints";
update data_element set validation_message = "Must not be blank" where name = "xReadMaxPrints";
update data_element set is_allow_empty = 0 where name = "xReadMaxPrints";
update data_element set validation_expression = '^\\d+$' where name = "zReadMaxPrints";
update data_element set validation_message = "Must not be blank" where name = "zReadMaxPrints";
update data_element set is_allow_empty = 0 where name = "zReadMaxPrints";
update data_element set options = "0|1|2" where name = "gratuityTier";
update data_element set options = "pp|fx" where name = "dccProvider";
update data_element set options = "standalone|epos|both" where name = "mode";
update data_element set max_length = 16 where name = "alipayPartner";
update data_element set validation_expression = '^.{0,16}$' where name = "alipayPartner";
update data_element set validation_message = "Must be up to 16 characters long" where name = "alipayPartner";
update data_element set front_end_validate = 1 where name = "alipayPartner";
update data_element set max_length = 12 where name = "alipayMid";
update data_element set validation_expression = '^.{12}$' where name = "alipayMid";
update data_element set validation_message = "Must 12 characters long" where name = "alipayMid";
update data_element set front_end_validate = 1 where name = "alipayMid";
update data_element set max_length = 4 where name = "alipayMcc";
update data_element set validation_expression = '^.{4}$' where name = "alipayMcc";
update data_element set validation_message = "Must be 4 characters long" where name = "alipayMcc";
update data_element set front_end_validate = 1 where name = "alipayMcc";